# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- name: System.Debug
  value: true

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Linux Agent
  steps:



  - task: Application security testing@2025
    displayName: Application security testing
    inputs:
      projectName: 'RahulP-101'
      enableProxy: false
      enableSastScan: true
      CheckmarxService: 'SAST 67 server'
      enableSastBranching: false
      fullTeamName: 'CxServer'
      incScan: false
      generatePDFReport: true
      enableDependencyScan: false
      vulnerabilityThreshold: true
      engineConfigId: '6'
